const fs = require('fs');
const path = require('path');

/**
 * Build Tokens - Converts DTCG JSON tokens to CSS custom properties
 * Supports multi-brand theming with data-brand attribute selectors
 */

class TokenBuilder {
  constructor(inputPath, outputPath) {
    this.inputPath = inputPath;
    this.outputPath = outputPath;
    this.cssVariables = [];
  }

  /**
   * Main build process
   */
  build() {
    try {
      console.log('🚀 Starting token build process...');

      const tokenFiles = this.findTokenFiles();

      if (tokenFiles.length === 0) {
        throw new Error('No token files found in tokens directory');
      }

      tokenFiles.forEach((file) => {
        console.log(`📦 Processing: ${file}`);
        const tokens = this.loadTokenFile(file);
        this.validateTokenStructure(tokens);
        this.processTokens(tokens);
      });

      this.generateCSS();
      console.log('✅ Token build completed successfully!');
    } catch (error) {
      console.error('❌ Build failed:', error.message);
      process.exit(1);
    }
  }

  /**
   * Find all token JSON files
   */
  findTokenFiles() {
    const tokensDir = path.join(this.inputPath, 'tokens');

    if (!fs.existsSync(tokensDir)) {
      fs.mkdirSync(tokensDir, { recursive: true });
      return [];
    }

    return fs
      .readdirSync(tokensDir)
      .filter((file) => file.endsWith('.json'))
      .map((file) => path.join(tokensDir, file));
  }

  /**
   * Load and parse token file
   */
  loadTokenFile(filePath) {
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content);
  }

  /**
   * Validate token structure against contract
   */
  validateTokenStructure(tokens) {
    if (!tokens.version) {
      throw new Error('Token file missing version');
    }

    if (!tokens.tokens) {
      throw new Error('Token file missing tokens object');
    }

    const requiredCategories = [
      'color',
      'typography',
      'spacing',
      'radius',
      'elevation',
      'motion',
      'density',
    ];
    const missingCategories = requiredCategories.filter(
      (cat) => !tokens.tokens[cat]
    );

    if (missingCategories.length > 0) {
      throw new Error(
        `Missing required token categories: ${missingCategories.join(', ')}`
      );
    }
  }

  /**
   * Process tokens recursively
   */
  processTokens(tokens, brand = null) {
    const brandName = brand || tokens.brand || 'default';

    this.cssVariables.push({
      brand: brandName,
      variables: this.extractVariables(tokens.tokens, ''),
    });

    // Process mode overrides
    if (tokens.tokens.modes) {
      Object.entries(tokens.tokens.modes).forEach(([mode, overrides]) => {
        this.cssVariables.push({
          brand: brandName,
          mode: mode,
          variables: this.extractVariables(overrides, ''),
        });
      });
    }
  }

  /**
   * Extract CSS variables from token object
   */
  extractVariables(obj, prefix) {
    const variables = {};

    Object.entries(obj).forEach(([key, value]) => {
      const varName = prefix ? `${prefix}-${key}` : key;

      if (value && typeof value === 'object') {
        if (value.$value !== undefined) {
          // DTCG token format
          variables[varName] = value.$value;
        } else {
          // Nested object - recurse
          Object.assign(variables, this.extractVariables(value, varName));
        }
      }
    });

    return variables;
  }

  /**
   * Generate CSS output
   */
  generateCSS() {
    let css = `/**
 * Design Tokens - Auto-generated CSS Custom Properties
 * DO NOT EDIT MANUALLY - Generated by build-tokens.js
 * Generation Date: ${new Date().toISOString()}
 */\n\n`;

    // Group by brand
    const brandGroups = this.groupByBrand();

    Object.entries(brandGroups).forEach(([brand, data]) => {
      // Base tokens
      const selector =
        brand === 'default' ? ':root' : `:root[data-brand="${brand}"]`;

      css += `${selector} {\n`;
      Object.entries(data.base).forEach(([name, value]) => {
        css += `  --${name}: ${value};\n`;
      });
      css += `}\n\n`;

      // Mode-specific tokens
      Object.entries(data.modes).forEach(([mode, variables]) => {
        const modeSelector =
          brand === 'default'
            ? `:root[data-theme="${mode}"]`
            : `:root[data-brand="${brand}"][data-theme="${mode}"]`;

        css += `${modeSelector} {\n`;
        Object.entries(variables).forEach(([name, value]) => {
          css += `  --${name}: ${value};\n`;
        });
        css += `}\n\n`;
      });
    });

    // Write output
    const outputDir = path.dirname(this.outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(this.outputPath, css);
    console.log(`📝 Generated CSS: ${this.outputPath}`);
  }

  /**
   * Group variables by brand and mode
   */
  groupByBrand() {
    const groups = {};

    this.cssVariables.forEach(({ brand, mode, variables }) => {
      if (!groups[brand]) {
        groups[brand] = { base: {}, modes: {} };
      }

      if (mode) {
        if (!groups[brand].modes[mode]) {
          groups[brand].modes[mode] = {};
        }
        Object.assign(groups[brand].modes[mode], variables);
      } else {
        Object.assign(groups[brand].base, variables);
      }
    });

    return groups;
  }
}

// Execute build
const projectRoot = path.join(__dirname, '..');
const inputPath = path.join(projectRoot, 'projects', 'ui-tokens', 'src');
const outputPath = path.join(
  projectRoot,
  'projects',
  'ui-tokens',
  'src',
  'lib',
  'tokens.css'
);

const builder = new TokenBuilder(inputPath, outputPath);
builder.build();
